str = input()
start = input()
end = input()
temp = str
str = str.upper()
print(str)
str = str.lower()
print(str)
str = str.title()
print(str)
str = temp
print(str)
print(str.isalnum())
print(str.isalpha())
print(str.isdecimal())
print(str.isspace())
print(str.startswith(start))
print(str.endswith(end))
str = ''.join(list(reversed(str)))
print(str)
